#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
for f in $(ls *32.nasm); do
	nasm -f elf32 $f;
done;
gcc -B/usr/bin -B/usr/lib/gcc/x86_64-linux-gnu/7 -m32 -msse -O0 -no-pie *32.o cfs32c.c -o cfs32c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./cfs32c $pars